version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'
  red = '##f38ba8'
  yellow = '#f9e2af'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:pink'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:pink'
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if gt .Code 0}}p:pink{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{.Icon}} '
    foreground = 'p:os'
    background = ''
    type = 'os'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:blue'
    background = ''
    type = 'session'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'p:pink'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:blue>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:lavender'
    background = ''
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯ '
    foreground = 'p:pink'
    background = ''
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if gt .Code 0}}p:pink{{end}}']
